
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-microservice
  template:
    metadata:
      labels:
        app: node-microservice
    spec:
      containers:
        - name: node-container
          image: dodaharsha/node-microservice:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-microservice
spec:
  selector:
    app: node-microservice
  ports:
    - port: 80
      targetPort: 3000
